author:
  avatar           : "profile.png"
  name             : "Pradeep Singh"
  bio              : "PostDoc / Engineer at INRIA working on small foundation models, representation learning, and AI for biology data."
  location         : "Nice, France"
  employer         : "INRIA Center, Université Côte d'Azur"
  uri              : "https://pradeepsinghnitk.github.io"
  email            : "pradeep.singh@inria.fr"
  googlescholar    : "https://scholar.google.com/citations?user=VmelJF8AAAAJ"
  orcid            : "https://orcid.org/0000-0002-1215-7553"
  github           : "pradeepsinghnitk"
  linkedin         : "pradeep-singh-1a0335119"
